service: serverless

frameworkVersion: "3"

provider:
  name: aws
  profile: terraform-pessoal
  runtime: nodejs18.x
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendRawEmail"
      Resource: "*"

plugins:
  - serverless-offline
  - serverless-s3-sync

package:
  exclude:
    - .serverless/**
    - .git/**
    - package-lock.json
    - merge-pdf/**

resources:
  - ${file(resources.yml)}

functions:
  - ${file(functions.yml)}

custom:
  s3Sync:
    - bucketName: bucket-merge-pdf-frontend
      localDir: /merge-pdf/build